// Code generated by protoc-gen-go. DO NOT EDIT.
// source: challenge.proto

package challenge

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetImagesRequest struct {
	Number               uint32   `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetImagesRequest) Reset()         { *m = GetImagesRequest{} }
func (m *GetImagesRequest) String() string { return proto.CompactTextString(m) }
func (*GetImagesRequest) ProtoMessage()    {}
func (*GetImagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4819ccc01c0c0a11, []int{0}
}

func (m *GetImagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetImagesRequest.Unmarshal(m, b)
}
func (m *GetImagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetImagesRequest.Marshal(b, m, deterministic)
}
func (m *GetImagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetImagesRequest.Merge(m, src)
}
func (m *GetImagesRequest) XXX_Size() int {
	return xxx_messageInfo_GetImagesRequest.Size(m)
}
func (m *GetImagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetImagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetImagesRequest proto.InternalMessageInfo

func (m *GetImagesRequest) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type GetImagesResponse struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Prompt               string   `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Images               [][]byte `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetImagesResponse) Reset()         { *m = GetImagesResponse{} }
func (m *GetImagesResponse) String() string { return proto.CompactTextString(m) }
func (*GetImagesResponse) ProtoMessage()    {}
func (*GetImagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4819ccc01c0c0a11, []int{1}
}

func (m *GetImagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetImagesResponse.Unmarshal(m, b)
}
func (m *GetImagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetImagesResponse.Marshal(b, m, deterministic)
}
func (m *GetImagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetImagesResponse.Merge(m, src)
}
func (m *GetImagesResponse) XXX_Size() int {
	return xxx_messageInfo_GetImagesResponse.Size(m)
}
func (m *GetImagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetImagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetImagesResponse proto.InternalMessageInfo

func (m *GetImagesResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *GetImagesResponse) GetPrompt() string {
	if m != nil {
		return m.Prompt
	}
	return ""
}

func (m *GetImagesResponse) GetImages() [][]byte {
	if m != nil {
		return m.Images
	}
	return nil
}

type GetAlphanumericRequest struct {
	Length               uint32   `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Size                 uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAlphanumericRequest) Reset()         { *m = GetAlphanumericRequest{} }
func (m *GetAlphanumericRequest) String() string { return proto.CompactTextString(m) }
func (*GetAlphanumericRequest) ProtoMessage()    {}
func (*GetAlphanumericRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4819ccc01c0c0a11, []int{2}
}

func (m *GetAlphanumericRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAlphanumericRequest.Unmarshal(m, b)
}
func (m *GetAlphanumericRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAlphanumericRequest.Marshal(b, m, deterministic)
}
func (m *GetAlphanumericRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAlphanumericRequest.Merge(m, src)
}
func (m *GetAlphanumericRequest) XXX_Size() int {
	return xxx_messageInfo_GetAlphanumericRequest.Size(m)
}
func (m *GetAlphanumericRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAlphanumericRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAlphanumericRequest proto.InternalMessageInfo

func (m *GetAlphanumericRequest) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *GetAlphanumericRequest) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type GetAlphanumericResponse struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Prompt               string   `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Image                []byte   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAlphanumericResponse) Reset()         { *m = GetAlphanumericResponse{} }
func (m *GetAlphanumericResponse) String() string { return proto.CompactTextString(m) }
func (*GetAlphanumericResponse) ProtoMessage()    {}
func (*GetAlphanumericResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4819ccc01c0c0a11, []int{3}
}

func (m *GetAlphanumericResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAlphanumericResponse.Unmarshal(m, b)
}
func (m *GetAlphanumericResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAlphanumericResponse.Marshal(b, m, deterministic)
}
func (m *GetAlphanumericResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAlphanumericResponse.Merge(m, src)
}
func (m *GetAlphanumericResponse) XXX_Size() int {
	return xxx_messageInfo_GetAlphanumericResponse.Size(m)
}
func (m *GetAlphanumericResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAlphanumericResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAlphanumericResponse proto.InternalMessageInfo

func (m *GetAlphanumericResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *GetAlphanumericResponse) GetPrompt() string {
	if m != nil {
		return m.Prompt
	}
	return ""
}

func (m *GetAlphanumericResponse) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type GetQuestionsRequest struct {
	Number               uint32   `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Label                string   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQuestionsRequest) Reset()         { *m = GetQuestionsRequest{} }
func (m *GetQuestionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetQuestionsRequest) ProtoMessage()    {}
func (*GetQuestionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4819ccc01c0c0a11, []int{4}
}

func (m *GetQuestionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuestionsRequest.Unmarshal(m, b)
}
func (m *GetQuestionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuestionsRequest.Marshal(b, m, deterministic)
}
func (m *GetQuestionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuestionsRequest.Merge(m, src)
}
func (m *GetQuestionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetQuestionsRequest.Size(m)
}
func (m *GetQuestionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuestionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuestionsRequest proto.InternalMessageInfo

func (m *GetQuestionsRequest) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *GetQuestionsRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type GetQuestionsResponse struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Questions            []string `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQuestionsResponse) Reset()         { *m = GetQuestionsResponse{} }
func (m *GetQuestionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetQuestionsResponse) ProtoMessage()    {}
func (*GetQuestionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4819ccc01c0c0a11, []int{5}
}

func (m *GetQuestionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuestionsResponse.Unmarshal(m, b)
}
func (m *GetQuestionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuestionsResponse.Marshal(b, m, deterministic)
}
func (m *GetQuestionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuestionsResponse.Merge(m, src)
}
func (m *GetQuestionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetQuestionsResponse.Size(m)
}
func (m *GetQuestionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuestionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuestionsResponse proto.InternalMessageInfo

func (m *GetQuestionsResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *GetQuestionsResponse) GetQuestions() []string {
	if m != nil {
		return m.Questions
	}
	return nil
}

func init() {
	proto.RegisterType((*GetImagesRequest)(nil), "challenge.GetImagesRequest")
	proto.RegisterType((*GetImagesResponse)(nil), "challenge.GetImagesResponse")
	proto.RegisterType((*GetAlphanumericRequest)(nil), "challenge.GetAlphanumericRequest")
	proto.RegisterType((*GetAlphanumericResponse)(nil), "challenge.GetAlphanumericResponse")
	proto.RegisterType((*GetQuestionsRequest)(nil), "challenge.GetQuestionsRequest")
	proto.RegisterType((*GetQuestionsResponse)(nil), "challenge.GetQuestionsResponse")
}

func init() {
	proto.RegisterFile("challenge.proto", fileDescriptor_4819ccc01c0c0a11)
}

var fileDescriptor_4819ccc01c0c0a11 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x6e, 0xda, 0x40,
	0x14, 0x96, 0xed, 0x16, 0xc9, 0x4f, 0xa0, 0x96, 0x81, 0x82, 0x71, 0xdd, 0xe2, 0xce, 0x0a, 0x75,
	0x81, 0xa5, 0xf6, 0x04, 0x11, 0x91, 0x10, 0xcb, 0x38, 0x07, 0x88, 0xc6, 0x30, 0x31, 0x8e, 0xec,
	0x19, 0xe3, 0x19, 0xb2, 0xc8, 0x92, 0x2b, 0xe4, 0x68, 0xb9, 0x42, 0x8e, 0x90, 0x03, 0x44, 0x1e,
	0x1b, 0xdb, 0x10, 0xf2, 0x23, 0x65, 0xc7, 0xf7, 0xde, 0x9b, 0xef, 0xfb, 0xf8, 0xde, 0x33, 0x7c,
	0x5b, 0xae, 0x49, 0x1c, 0x53, 0x16, 0xd2, 0x69, 0x9a, 0x71, 0xc9, 0x91, 0x59, 0x15, 0x6c, 0x27,
	0xe4, 0x3c, 0x8c, 0xa9, 0x47, 0xd2, 0xc8, 0x23, 0x8c, 0x71, 0x49, 0x64, 0xc4, 0x99, 0x28, 0x06,
	0xf1, 0x5f, 0xf8, 0x3e, 0xa7, 0x72, 0x91, 0x90, 0x90, 0x0a, 0x9f, 0x6e, 0xb6, 0x54, 0x48, 0x34,
	0x80, 0x16, 0xdb, 0x26, 0x01, 0xcd, 0x2c, 0xcd, 0xd5, 0x26, 0x1d, 0xbf, 0x44, 0x38, 0x80, 0x6e,
	0x63, 0x56, 0xa4, 0x9c, 0x09, 0x8a, 0x7e, 0x01, 0x08, 0x2a, 0x44, 0xc4, 0xd9, 0x55, 0xb4, 0x52,
	0x0f, 0x4c, 0xdf, 0x2c, 0x2b, 0x8b, 0x55, 0xce, 0x95, 0x66, 0x3c, 0x49, 0xa5, 0xa5, 0xab, 0x56,
	0x89, 0xf2, 0x7a, 0xa4, 0x88, 0x2c, 0xc3, 0x35, 0x26, 0x6d, 0xbf, 0x44, 0xf8, 0x1c, 0x06, 0x73,
	0x2a, 0xcf, 0xe2, 0x74, 0x4d, 0xd8, 0x36, 0xa1, 0x59, 0xb4, 0x6c, 0xb8, 0xca, 0xff, 0x90, 0x5c,
	0xef, 0x5d, 0x15, 0x08, 0x21, 0xf8, 0x22, 0xa2, 0x3b, 0xaa, 0xf8, 0x3b, 0xbe, 0xfa, 0x8d, 0xaf,
	0x61, 0xf8, 0x82, 0xe5, 0x73, 0x7e, 0xfb, 0xf0, 0x55, 0x39, 0xb4, 0x0c, 0x57, 0x9b, 0xb4, 0xfd,
	0x02, 0xe0, 0x19, 0xf4, 0xe6, 0x54, 0x5e, 0xe4, 0xfe, 0xf2, 0x4c, 0xdf, 0x09, 0x30, 0x27, 0x89,
	0x49, 0x40, 0xe3, 0x92, 0xbb, 0x00, 0xf8, 0x12, 0xfa, 0x87, 0x24, 0x1f, 0x73, 0xea, 0x80, 0xb9,
	0xd9, 0xbf, 0xb1, 0x74, 0xd7, 0xc8, 0xbb, 0x55, 0xe1, 0xdf, 0x93, 0x0e, 0xe6, 0x6c, 0x7f, 0x03,
	0xe8, 0x06, 0x50, 0xb5, 0xb9, 0xba, 0xfa, 0x73, 0x5a, 0x9f, 0xcd, 0xf1, 0x11, 0xd8, 0xce, 0xe9,
	0x66, 0xe1, 0x0d, 0x8f, 0x76, 0x0f, 0x8f, 0xf7, 0x7a, 0x0f, 0x75, 0xbd, 0x6a, 0xca, 0x2b, 0x36,
	0x88, 0x76, 0x1a, 0x58, 0x47, 0xe1, 0xd7, 0x92, 0x7f, 0x0e, 0x59, 0x4f, 0xec, 0xd9, 0xc6, 0x6f,
	0x8d, 0x94, 0xf2, 0x63, 0x25, 0x3f, 0x42, 0xc3, 0x86, 0x3c, 0x69, 0x0c, 0xa2, 0x5b, 0xf8, 0xd1,
	0xcc, 0xb4, 0x36, 0xf0, 0xfb, 0x90, 0xfd, 0x78, 0x75, 0xf6, 0xf8, 0xd5, 0x7e, 0x29, 0xed, 0x28,
	0xe9, 0x01, 0xea, 0x37, 0xa4, 0xab, 0xd8, 0x83, 0x96, 0xfa, 0xaa, 0xfe, 0x3f, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x9d, 0x40, 0x6f, 0x6e, 0x91, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ChallengeClient is the client API for Challenge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChallengeClient interface {
	// Get an image challenge
	//
	// Returns a list of images and a prompt that lets the client know which images we are asking for.
	GetImagesChallenge(ctx context.Context, in *GetImagesRequest, opts ...grpc.CallOption) (*GetImagesResponse, error)
	// Get an alphanumeric challenge
	//
	// Returns an image with alphanumeric characters to be found, and a prompt if applicable
	GetAlphanumericChallenge(ctx context.Context, in *GetAlphanumericRequest, opts ...grpc.CallOption) (*GetAlphanumericResponse, error)
	// Get a questions list challenge
	//
	// Returns a list of questions that are to be answered by the client.
	GetQuestionsChallenge(ctx context.Context, in *GetQuestionsRequest, opts ...grpc.CallOption) (*GetQuestionsResponse, error)
}

type challengeClient struct {
	cc grpc.ClientConnInterface
}

func NewChallengeClient(cc grpc.ClientConnInterface) ChallengeClient {
	return &challengeClient{cc}
}

func (c *challengeClient) GetImagesChallenge(ctx context.Context, in *GetImagesRequest, opts ...grpc.CallOption) (*GetImagesResponse, error) {
	out := new(GetImagesResponse)
	err := c.cc.Invoke(ctx, "/challenge.Challenge/GetImagesChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *challengeClient) GetAlphanumericChallenge(ctx context.Context, in *GetAlphanumericRequest, opts ...grpc.CallOption) (*GetAlphanumericResponse, error) {
	out := new(GetAlphanumericResponse)
	err := c.cc.Invoke(ctx, "/challenge.Challenge/GetAlphanumericChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *challengeClient) GetQuestionsChallenge(ctx context.Context, in *GetQuestionsRequest, opts ...grpc.CallOption) (*GetQuestionsResponse, error) {
	out := new(GetQuestionsResponse)
	err := c.cc.Invoke(ctx, "/challenge.Challenge/GetQuestionsChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChallengeServer is the server API for Challenge service.
type ChallengeServer interface {
	// Get an image challenge
	//
	// Returns a list of images and a prompt that lets the client know which images we are asking for.
	GetImagesChallenge(context.Context, *GetImagesRequest) (*GetImagesResponse, error)
	// Get an alphanumeric challenge
	//
	// Returns an image with alphanumeric characters to be found, and a prompt if applicable
	GetAlphanumericChallenge(context.Context, *GetAlphanumericRequest) (*GetAlphanumericResponse, error)
	// Get a questions list challenge
	//
	// Returns a list of questions that are to be answered by the client.
	GetQuestionsChallenge(context.Context, *GetQuestionsRequest) (*GetQuestionsResponse, error)
}

// UnimplementedChallengeServer can be embedded to have forward compatible implementations.
type UnimplementedChallengeServer struct {
}

func (*UnimplementedChallengeServer) GetImagesChallenge(ctx context.Context, req *GetImagesRequest) (*GetImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImagesChallenge not implemented")
}
func (*UnimplementedChallengeServer) GetAlphanumericChallenge(ctx context.Context, req *GetAlphanumericRequest) (*GetAlphanumericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlphanumericChallenge not implemented")
}
func (*UnimplementedChallengeServer) GetQuestionsChallenge(ctx context.Context, req *GetQuestionsRequest) (*GetQuestionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestionsChallenge not implemented")
}

func RegisterChallengeServer(s *grpc.Server, srv ChallengeServer) {
	s.RegisterService(&_Challenge_serviceDesc, srv)
}

func _Challenge_GetImagesChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChallengeServer).GetImagesChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/challenge.Challenge/GetImagesChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChallengeServer).GetImagesChallenge(ctx, req.(*GetImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Challenge_GetAlphanumericChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlphanumericRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChallengeServer).GetAlphanumericChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/challenge.Challenge/GetAlphanumericChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChallengeServer).GetAlphanumericChallenge(ctx, req.(*GetAlphanumericRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Challenge_GetQuestionsChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChallengeServer).GetQuestionsChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/challenge.Challenge/GetQuestionsChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChallengeServer).GetQuestionsChallenge(ctx, req.(*GetQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Challenge_serviceDesc = grpc.ServiceDesc{
	ServiceName: "challenge.Challenge",
	HandlerType: (*ChallengeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetImagesChallenge",
			Handler:    _Challenge_GetImagesChallenge_Handler,
		},
		{
			MethodName: "GetAlphanumericChallenge",
			Handler:    _Challenge_GetAlphanumericChallenge_Handler,
		},
		{
			MethodName: "GetQuestionsChallenge",
			Handler:    _Challenge_GetQuestionsChallenge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "challenge.proto",
}
